# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Portfolio Neal Jander
subtitle: A portfolio of the work of Neal Jander
description: > # this means to ignore newlines until "baseurl:"
  This is the description of my site and what it is etc.
keywords: demo blog example

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jwillmer.github.io/jekyllDecent" # the base hostname & protocol for your site
permalink: /blog/:categories/:title
cover: /assets/mountain3.jpg

# Build settings
markdown: kramdown
include: ['_pages']
exclude: [vendor]
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from